#pragma once

#define NATURAL_NUMBER 2.73f
#define FIBONNACCI_NUMBER 1.618f
#define WIERD_NUMBER(NATURAL_NUMBER, FIBONNACCI_NUMBER) NATURAL_NUMBER + FIBONNACCI_NUMBER

// Détruie la variable
#undef WIERD_NUMBER

#define WIERD_NUMBER(NATURAL_NUMBER, FIBONNACCI_NUMBER) NATURAL_NUMBER + FIBONNACCI_NUMBER